apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres-database
spec:
  instances: 1
  
  # Правильные отступы для блока bootstrap
  bootstrap:
    initdb:
      database: my_app_db
      owner: my_user
      secret:
        name: my-db-secret

  storage:
    size: 5Gi
    storageClass: standard
