mode: standalone
replicas: 1

rootUser: "admin"
rootPassword: "password"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

persistence:
  size: 5Gi

ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - minio.lakehouse.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m

consoleIngress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - console.minio.lakehouse.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m

buckets:
  - name: lakehouse
    policy: none
    purge: false
  - name: airflow
    policy: none
    purge: false
  - name: risingwave
    policy: none
    purge: false
  - name: kafka
    policy: none
    purge: false
